FROM node:20
WORKDIR /usr/src/app
COPY package*.json ./
RUN npm install
COPY . .
COPY .env.example .env
COPY docker-entrypoint-cronjob.sh .
RUN chmod +x docker-entrypoint-cronjob.sh

ENTRYPOINT ["/usr/src/app/docker-entrypoint-cronjob.sh"]
